### ISSUE TITLE
use  case comments

### ISSUE THREAD

**Issue by jcolomb** [pkraker/open-discovery#5]
Hi.
The use case has some flaws. 1 year phd students do not start writing his thesis and one should start his literature search much sooner. Maybe a scenario where a postdoc or even a PI is entering a new field would be more convincing ( prof. X is working on the role of prot. Y in the eye development in the mouse. Y was recently shown to be involved in olfactory learning in flies. Prof X is looking at this new field, but does not know where to start(new topic, fifferent model system, different communities,...)

The bubble visualisation is not clear to me, the phone analogy is also not straightforward.

**Comment by pkraker** [comment]
Julien, thanks for your feedback. I like your suggestion about a more senior researcher, as this is a scenario that I have encountered myself and where I think that a tool like Blaze would be indeed very helpful (esp. in interdisciplinary contexts as you have pointed out). So this is something we should think about. We settled on the first year PhD student because we saw this scenario as more relatable to a wider audience. Maybe we should even have two use cases.

Regarding Sarah, do you think it would be better to understand if we talked about "her PhD project" rather than "her thesis"? From my experience, the major outcome of the first year of many PhD programmes is a comprehensive literature review. It seems that you have experienced a different approach. Could you shortly outline the stages in the approach/timeplan that you are familiar with?

Regarding the bubble visualization, we should definitely include an image or at least a link to the prototype (e.g. http://openknowledgemaps.org/mozfest/index.php?id=zika). Now that you mentioned it, I can see that the phone analogy is not straightforward, especially if you haven't interacted with the visualization yet. And even then it's probably not as obious as I thought (I was referring to the main screen showing the apps and the ability to zoom into groups of apps).

A lot of food for thought - thank you very much again!

**Comment by jcolomb** [comment]
Hey.
Thanks for the nice words.

  In my experience (switzerland,france,germany), PhD programs are a joke: the student has one mentor who got money for the project, he is given a project, a technical supervisor and here it goes. Writing comes in the third/fourth year, with close to no training before that point.
They are supposed to get familiar with thr project and the literature over the first 6 months/1 year , though. At that time, they should be able to make new propositions and be part of the experimental design. Some are much faster, some never get to that point...
Postdocs and pi may be an easier target, because they have an idea about what they are looking for. Phd students do not: the value proposition of BLAZE appears only once one goes via the process "by hand" once, doesn't it?

Best luck

**Comment by pkraker** [comment]
I think that BLAZE would be nice supplementary tool, even when someone guides your discovery process. Your supervisor could even start you off with an existing map and then you to start mapping one of the sub-areas. And if you have no guidance (a thing that is not unheard of), BLAZE will assist you better than existing tools and connect you with the community in the field.

Thanks for the clarification on the timeline. We've updated the text in the [main use case](https://github.com/pkraker/open-discovery/blob/master/proposal.md#main-use-case) now to reflect that better.
